// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var AppLayout$Danielmain = require("./AppLayout.bs.js");

function App$App(Props) {
  return React.createElement(AppLayout$Danielmain.make, {});
}

var App = {
  make: App$App
};

ReactDOMRe.renderToElementWithId(React.createElement(App$App, {}), "root");

exports.App = App;
/*  Not a pure module */
