// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var Core = require("@material-ui/core");
var Styles = require("@material-ui/core/styles");
var MaterialUi_ThemeProvider = require("@jsiebern/bs-material-ui/src/MaterialUi_ThemeProvider.bs.js");

var useStyles = Styles.makeStyles({
      container: {
        height: "100%",
        margin: "30px auto",
        maxWidth: "970px",
        width: "100%"
      }
    });

var Styles$1 = {
  useStyles: useStyles
};

function AppLayout(Props) {
  var classes = Curry._1(useStyles, undefined);
  return React.createElement(MaterialUi_ThemeProvider.make, {
              children: React.createElement("div", {
                    className: classes.container
                  }, React.createElement(Core.CssBaseline, {}), React.createElement(Core.Grid, {
                        children: React.createElement(Core.Grid, {
                              children: React.createElement(Core.Typography, {
                                    children: "@jsiebern/bs-material-ui Examples",
                                    variant: "h4"
                                  }),
                              item: true,
                              md: MaterialUi_Grid.Md._12
                            }),
                        container: true
                      }), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "Class Override",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "Icons",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "Popover",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "WithStylesSafe",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "WithStylesUnsafe",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "Theme Provider",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "Theme Provider Override",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "List",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: React.createElement("a", {
                                        href: "https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/tabs/DisabledTabs.tsx",
                                        target: "_blank"
                                      }, "Tabs"),
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: React.createElement("a", {
                                        href: "https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/steppers/VerticalLinearStepper.tsx",
                                        target: "_blank"
                                      }, "Stepper"),
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: React.createElement("a", {
                                        href: "https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/selects/SimpleSelect.tsx",
                                        target: "_blank"
                                      }, "Select"),
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: React.createElement("a", {
                                        href: "https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/slider/InputSlider.tsx",
                                        target: "_blank"
                                      }, "Slider"),
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: React.createElement("a", {
                                        href: "https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/slider/InputSlider.tsx",
                                        target: "_blank"
                                      }, "Dashboard"),
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: React.createElement("a", {
                                        href: "https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/box/box.md",
                                        target: "_blank"
                                      }, "Box"),
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: React.createElement("a", {
                                        href: "https://github.com/mui-org/material-ui/blob/master/docs/src/pages/styles/api/api.md#serverstylesheets",
                                        target: "_blank"
                                      }, "ServerStyleSheets"),
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: "TextField size Prop",
                                  variant: "h5"
                                }),
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          }), React.createElement(Core.Grid, {
                            item: true,
                            md: MaterialUi_Grid.Md._6
                          })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined)),
              theme: Styles.createMuiTheme({})
            });
}

var make = AppLayout;

exports.Styles = Styles$1;
exports.make = make;
/* useStyles Not a pure module */
