// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");

function Index$App(Props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "Daniel Main profile"));
}

var App = {
  make: Index$App
};

ReactDOMRe.renderToElementWithId(React.createElement(Index$App, {}), "root");

exports.App = App;
/*  Not a pure module */
