// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Core = require("@material-ui/core");
var MaterialUi_IconButton = require("@jsiebern/bs-material-ui/src/MaterialUi_IconButton.bs.js");
var Menu = require("@material-ui/icons/Menu").default;
var Styles = require("@material-ui/core/styles");

var useStyles = Styles.makeStyles({
      avatar: {
        height: "100",
        width: "100"
      },
      menuContainer: {
        display: "flex",
        alignItems: "center"
      },
      title: {
        flexGrow: "1"
      },
      menuButton: {
        marginRight: "2"
      },
      root: {
        flexGrow: "1"
      }
    });

var Styles$1 = {
  useStyles: useStyles
};

function MainPage(Props) {
  var classes = Curry._1(useStyles, undefined);
  return React.createElement(Core.AppBar, {
              children: React.createElement(Core.Toolbar, {
                    children: React.createElement("div", undefined, React.createElement("div", {
                              className: classes.menuContainer
                            }, React.createElement(Core.IconButton, {
                                  children: React.createElement(Menu, {}),
                                  className: classes.menuButton,
                                  color: "inherit",
                                  edge: MaterialUi_IconButton.Edge.start
                                }), React.createElement(Core.Typography, {
                                  children: "Timeline",
                                  className: classes.title,
                                  variant: "h6"
                                })), React.createElement("div", {
                              className: classes.menuContainer
                            }, React.createElement(Core.Avatar, {
                                  alt: "Remy Sharp",
                                  className: classes.avatar,
                                  src: "https://avatars0.githubusercontent.com/u/4303099?s=400&u=fdc8480753f4ecb01d6ad7da9b94d0df93ca8ab2&v=4"
                                })))
                  }),
              position: "static"
            });
}

var make = MainPage;

exports.Styles = Styles$1;
exports.make = make;
/* useStyles Not a pure module */
